### ISSUE TITLE
response of /v1/provide-historical-pm-data-... gives empty list of performance measurements

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/AutomatedLinkAcceptanceProxy#355]
The list of _**air-interface-performance-measurements**_ as well as the list of **_ethernet-container-performance-measurements_** contains only empty objects.

**Comment by jain-siae** [comment]
Hi @anacabbar , ok we will investigate. Can you provide the exact output ?

**Comment by latta-siae** [comment]
@anacabbar please provide error code in the response / logs in the container

Seems 200 code return without any useful logs
To be reproduce in SIAE environement

**Comment by anacabbar** [comment]
As you requested earlier, here an example of that the empty output for performance measurements look like. As mentioned in today's meeting, this happened for all the mountNames that were randomly tested.

For air interfaces:
```
 "air-interface-performance-measurements-list": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ]
    }
  ],
```

And for ethernet containers:

  ```
   
"ethernet-container-performance-measurements-list": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ]
```

**Comment by jain-siae** [comment]
Hi @anacabbar  From the below issue , we are depicting that response is coming for the devices , however some parameters as mentioned in the issue are not coming 
https://github.com/openBackhaul/AccessPlanningToolProxy/issues/356
If it is the case , then can we close this issue?

**Comment by anacabbar** [comment]
Hello @jain-siae ,

Please review this issue with greater attention. 

The ControlConstruct of all devices (retrieved from the MWDI) contain entries of historical performance data. However, the APTP is not delivering this data for any single device; the data sent in the request is looking like in my comment above. 

Apart from missing the relevant data, looking at the reponses for  **_"air-interface-performance-measurements-list"_** and **_"ethernet-container-performance-measurements-list"_** (like in the example above), the body seems wrong with respect to the json schema:
-->Both **_"air-interface-performance-measurements-list"_** and **_"ethernet-container-performance-measurements-list"_** should be an array of objects, but the response is looking like an array of empty arrays.

See the OpenAPI specification.

```
                                  air-interface-performance-measurements-list:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        granularity-period:
                                          type: string
                                          enum:
                                            - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
                                            - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS'
                                            - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-UNKNOWN'
                                            - 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-NOT_YET_DEFINED'
                                          description: >
                                            'Time period between reset of the underlying counter
                                            from {$RequestForProvidingHistoricalPmDataCausesReadingHistoricalAirInterfacePerformanceFromCache.AirInterfaceHistoricalPmFromCache.response.body#air-interface-2-0:air-interface-historical-performance/historical-performance-data-list/granularity-period}'
                                        period-end-time:
                                          type: string
                                          description: >
                                            'Time when the counter values have been recorded and the counter reset
                                            from {$RequestForProvidingHistoricalPmDataCausesReadingHistoricalAirInterfacePerformanceFromCache.AirInterfaceHistoricalPmFromCache.response.body#air-interface-2-0:air-interface-historical-performance/historical-performance-data-list/period-end-time}'
                                        transmit-level-minimum:

                               ...
```
