### ISSUE TITLE
Improve understandability of description for attribute retrieval in callbacks

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AutomatedLinkAcceptanceProxy#49]
Example: in the response of */v1/provide-acceptance-data-of-link-endpoint* there's the attribute *configured-modulation-minimum*:

```
                      configured-modulation-minimum:
                        type: object
                        description: 'Configured minimum modulation scheme'
                        properties:
                          number-of-states:
                            type: integer
                            description: >
                              'Number of states in the phase diagram (e.g. BPSK->2 or 256QAM->256)
                              transmissionModeMin = {$RequestForProvidingAcceptanceDataCausesReadingConfigurationFromCache.response.body#air-interface-2-0:air-interface-configuration/transmission-mode-min}
                              from {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/modulation-scheme} for {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/transmission-mode-name} == transmissionModeMin'
```        
With example data:                 
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/57349523/4155d84b-b524-4ee9-bb67-70a8b686ba74)

The description is not wrong, but could be improved for easier understandability:
```
description: >
  'Number of ...
   WITH transmissionModeMin = blablabla,
   from {xxx} WHERE {yyy}
```
(or keep the from {xxx} FOR {yyy})

There are multiple attributes where the description is in the same format as shown above.
