### ISSUE TITLE
Include complete paths in descriptions on how to retrieve attribute values

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AutomatedLinkAcceptanceProxy#52]
**Solution:**
Use fully qualified paths in descriptions, i.e.
```
description: >
  ' blablabla
   from {$callbackname.response.body#path-to-attribute1 for $callbackname.response.body#path-to-attribute2 == xyz}'
```

proposal for better readability:
```
            description: >
              'blablabla
               WITH 
                   {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/uuid} as uuid,
                   {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/layer-protocol/layer-protocol-name} as layer-protocol-name
              from {$uuid for $layer-protocol-name == air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER}'
```

Also see companion issue #49.

---

**Description:**
Example in RequestForProvidingAcceptanceDataCausesDeterminingAirInterfaceUuidUnderTest.AirInterfaceName callback:
uuid description does not have a complete path for the 2nd attribute:
```
          - name: uuid
            in: path
            required: true
            schema:
              type: string
              example: 'LTP-MWPS-TTP-1-1'
            description: >
              'The UUID of the LogicalTerminationPoint that is addressed by the request
              from {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/uuid for ./layer-protocol/layer-protocol-name == air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER}'
```

The path for the layer-protocol-name should also be stated explicitly, even if this leads to a longer description, i.e.:
```
            description: >
              'The UUID of the LogicalTerminationPoint that is addressed by the request
              from {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/uuid for $RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/layer-protocol/layer-protocol-name == air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER}'
```

Also as proposed in #49 a WITH statement could be used, e.g.
```
            description: >
              'blablabla
               WITH RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point as callback-path,
              from {$callback-path/uuid for $callback-path/layer-protocol/layer-protocol-name == air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER}'
```

or (see proposal under solution)
```
            description: >
              'blablabla
               WITH 
                   {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/uuid} as uuid,
                   {$RequestForProvidingAcceptanceDataCausesReadingLtpStructure.response.body#core-model-1-4:control-construct/logical-termination-point/layer-protocol/layer-protocol-name} as layer-protocol-name
              from {$uuid for $layer-protocol-name == air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER}'
```
